;;; init.el --- My init.el auto-generated by leaf-manager  -*- lexical-binding: t; -*-

;; Copyright (C) 2020-2022 Hunter Jozwiak

;; Author: Hunter Jozwiak <sektor@tekunen>

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; The main loader for modules.

;;; Code:

(customize-set-variable 'custom-file "custom.el")
(when (file-exists-p custom-file)
(load custom-file))
(customize-set-variable 'package-archives
			  '(("melpa" . "https://melpa.org/packages/")
			    ("gnu" . "https://elpa.gnu.org/packages/")))
  (package-initialize)
  (unless (package-installed-p 'leaf)
    (package-refresh-contents)
    (package-install 'leaf))
  (leaf leaf-keywords
    :ensure t
    :init
    (leaf hydra
      :ensure t)

    (leaf blackout
      :ensure t)

    :config
    (leaf-keywords-init))
(leaf no-littering)
(add-to-list 'load-path (expand-file-name "modules/" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "emacspeak/lisp/" user-emacs-directory))
(require 'builtins)
