;;; init.el --- My configuration for Emacs.        -*- lexical-binding: t; -*-

;; Copyright (C) 2022  Hunter Jozwiak

;; Author: Hunter Jozwiak <hunter.t.joz@gmail.com>
;; Keywords: config

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Do not edit this file directly; it is tangled from init.org
;;; Code:


(set-default-coding-systems 'utf-8)

(customize-set-variable 'custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
(load custom-file))

(customize-set-variable 'package-archives
                          '(("melpa" . "https://melpa.org/packages/")))

(package-initialize)
(unless (package-installed-p 'quelpa)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
    (eval-buffer)
    (quelpa-self-upgrade)))

(unless (package-installed-p 'use-package)
  (quelpa 'use-package)
(require 'use-package)
(customize-variable 'use-package-ensure-function #'quelpa)

(use-package no-littering :ensure t)

(use-package general
  :ensure t
  :config
  (general-evil-setup)
  (general-create-definer mapleader
    :prefix "SPC"
    :global-prefix "C-SPC"
    :keymaps 'override
    :states '(normal visual emacs insert))
    (mapleader
  "b" '(:ignore t :which-key "Buffer management")
  "bb" '(switch-to-buffer :which-key "Buffer management")
  "bn" '(next-buffer :which-key "Next buffer")
  "bd" '(evil-delete-buffer :which-key "Kill a buffer")
  "bp" '(previous-buffer :which-key "Previous buffer")
  "br" '(revert-buffer :which-key "Revert the current buffer")
  "f" '(:ignore t :which-key "Files")
  "ff" '(find-file :which-key "Find a file on disk")
  "fs" '(save-buffer :which-key "Save changes")
  "F" '(:ignore t :which-key "Frames")
  "Fo" '(other-frame :which-key "Other frame")
  "g" '(:ignore t :which-key "Git operations")
  "h" '(:ignore t :which-key "Get help")
  "hd" '(:ignore t :which-key "Describe parts of Emacs")
  "hdb" '(describe-bindings :which-key "Describe the bindings that are in effect")
  "hdB" '(general-describe-keybindings :which-key "Show the bindings that General has defined.")
  "hdf" '(describe-function :which-key "Describe a function")
  "hdF" '(describe-face :which-key "Describe a face")
  "hdk" '(describe-key :which-key "Show the documentation for the function associated with key")
  "hdv" '(describe-variable :which-key "Show the docs for a variable")
  "hi" '(:ignore t :which-key "info things")
  "hii" '(info :which-key "Enter the info index")
  "q" '(:ignore t :which-key "Closing Emacs itself or frames within.")
  "qQ" '(kill-emacs :which key "Leave Emacs.")))

(use-package exec-path-from-shell
  :ensure t
  :config
  (exec-path-from-shell-initialize))

(add-to-list 'load-path (expand-file-name "emacspeak/lisp/" user-emacs-directory))

(use-package emacs
  :custom
  (auto-save-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (inhibit-startup-message t)
   (indent-tabs-mode nil)
   (tool-bar-mode nil)
   (menu-bar-mode nil)
   (scroll-bar-mode nil)
   (user-full-name "Hunter Jozwiak")
   (user-mail-address "hunter.t.joz@gmail.com")
   (user-login-name "sektor")
   (use-short-answers t))

(use-package autorevert
  :custom
  (auto-revert-interval 0.1)
:config
    (global-auto-revert-mode))

(use-package recentf
  :config (recentf-mode))

(use-package savehist
  :config (savehist-mode))

(use-package windmove
  :general
  (mapleader
    "w" '(:ignore t :which-key "Window operations")
    "wh" '(windmove-left :which-key "Select the window to the left")
    "wl" '(windmove-right :which-key "Select the window to the right")
    "wj" '(windmove-down :which-key "Select the window below")
    "wk" '(windmove-up :which-key "Select window above")))
  (use-package winner
    :general
    (mapleader
      "wr" '(winner-redo :which-key "Restore a window configuration")
      "wu" '(winner-redo :which-key "Restore a window configuration"))
    :config
    (winner-mode))

(use-package auth-source
  :custom
  (auth-source-cache-expiry nil))
(use-package auth-source-pass
  :custom
  (auth-sources '("~/.authinfo.gpg" password-store))
  :config
  (auth-source-pass-enable))

(use-package epa
  :custom
  (epa-pinentry-mode 'loopback))

(use-package emacspeak-setup
  :custom
  (espeak-default-speech-rate 820)
   (emacspeak-character-echo nil)
   (emacspeak-word-echo nil))

(use-package orderless
  :ensure t
  :custom
  (completion-category-overrides '((file (styles . (basic partial-completion)))))
  (completion-styles '(orderless basic)))

(use-package vertico
  :custom (vertico-count 20)
           (vertico-cycle t)
  :ensure t
  :general
   (vertico-map
   "C-J" 'vertico-next
   "C-k" 'vertico-previous)
   :init
   (vertico-mode 1))
(use-package vertico-directory
             :after vertico
    :general
     (vertico-map
     "C-l" 'vertico-directory-enter
     "C-h" 'vertico-directory-up))

(use-package marginalia
  :ensure t
  :config (marginalia-mode))

(use-package consult
  :ensure t
  :demand t
  :custom
  (completion-in-region-function #'consult-completion-in-region)
  :general
   ([remap switch-to-buffer] 'consult-buffer))

(use-package embark
  :ensure t
  :demand t
  :general
   ([remap describe-bindings] 'embark-bindings
   "C-." 'embark-act))

(use-package embark-consult
             :ensure t
             :after (embark consult)
    :hook (embark-collect-mode . consult-preview-at-point-mode))

(use-package company
  :ensure t
  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.0)
  :init
  (global-company-mode))
(use-package company-box
  :ensure t
  :hook (company-mode . company-box-mode))

(use-package yasnippet
  :ensure t
  :init
  (yas-global-mode 1))
(use-package yasnippet-snippets
  :ensure t
  :after yasnippet)

(use-package ement
  :custom
  (ement-initial-sync-timeout 3600)
  :quelpa (ement :fetcher github :repo "alphapapa/ement.el"))

(use-package undo-tree
  :ensure t
  :init
  (global-undo-tree-mode 1))

(use-package evil
             :ensure t
             :custom
             (evil-want-integration t)
             (evil-want-C-i-jump nil)
             (evil-want-keybind nil)
             (evil-undo-system 'undo-tree)
             :init
             (evil-mode 1))

(use-package evil-collection
  :ensure t
             :after evil
             :config
             (evil-collection-init))

(use-package org
  :preface
  (defun org-setup ()
    "Hook functions for when we enter an org buffer, not provided by any other major mode."
    (prettify-symbols-mode 1)
    (variable-pitch-mode 1))
  :hook (org-mode . org-setup))

(use-package org-appear
  :ensure t
  :after org
  :hook (org-mode . org-appear-mode))

(use-package evil-org
  :ensure t
  :after org
  :hook (org-mode . evil-org-mode)
  :config
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))

(use-package org-make-toc
  :ensure t)

(use-package eglot
  :commands eglot-ensure
  :ensure t
  :custom
  (eglot-autoshutdown t))

(use-package flycheck
  :ensure t
  :init
  (global-flycheck-mode 1))

(use-package smartparens
  :ensure t
  :init
  (smartparens-strict-mode 1))

(use-package sly
  :custom (inferior-lisp-program "sbcl")
  :hook (lisp-mode . sly-editing-mode)
  :ensure t)
(use-package sly-asdf
  :after sly
  :ensure t)
(use-package sly-quicklisp
  :after sly
  :ensure t)

(use-package geiser
  :ensure t
  :custom (scheme-program-name "guile"))
(use-package geiser-guile
  :ensure t)

(use-package project
  :general
  (mapleader
    "SPC" '(consult-project-buffer :which-key "Switch to a buffer in a project")
    "p" '(:ignore t :which-key "Project operations.")
    "pa" '(project-remember-project :which-key "Add a project to the list")
    "pc" '(project-compile :which-key "Compile the project")
    "pf" '(project-find-file :which-key "Search for a file within a project")
    "pp" '(project-switch-project :which-key "Switch to a project")
    "ps" '(magit-project-status :which-key "Git status of a project")
    :init
    (unless (file-exists-p project-list-file)
      (project-remember-projects-under "~/projects")
      (project-remember-project "~/.emacs.d/"))))

(use-package magit
  :ensure t
  :custom
  (magit-delete-by-moving-to-trash nil)
  :commands magit-add-section-hook magit-status magit-stage-file
  :general
  (mapleader
    "gg" '(magit-status :which-key "Magit status")
    "gs" '(magit-stage-file :which-key "Stage the current working file."))
  :config
  (magit-add-section-hook 'magit-status-sections-hook 'magit-insert-modules 'magit-insert-stashes 'append))

(use-package forge
             :ensure t
             :after magit
             :general
             (mapleader
               "gf" '(forge-dispatch :which-key "Forge dispatching map.")))

(use-package magit-gitflow
    :ensure t
    :hook (magit-mode . turn-on-magit-gitflow))

(use-package git-timemachine
    :ensure t
    :general
    (mapleader
      "gt" '(git-timemachine-toggle :which-key "Toggle the time machine")))

(use-package nix-mode
  :ensure t
  :mode "\\.nix\\'")

(use-package kubernetes
  :ensure t
  :general
  (mapleader
    "k" '(:ignore t :which-key "Kubernetes operations")
    "ko" '(kubernetes-overview :which-key "Get an overview")))

(use-package helpful
  :ensure t
  :general
   ([remap describe-function] 'helpful-callable
   [remap describe-key] 'helpful-key
   [remap describe-variable] 'helpful-variable))

(use-package which-key
  :ensure t
  :init
  (which-key-mode 1))

(use-package restart-emacs
  :ensure t
  :general
  (mapleader
   "qr" '(restart-emacs :which-key "Restart Emacs")))

;;; init.el ends here
