;;; init.el --- My configuration for Emacs.        -*- lexical-binding: t; -*-

;; Copyright (C) 2022  Hunter Jozwiak

;; Author: Hunter Jozwiak <hunter.t.joz@gmail.com>
;; Keywords: config

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Do not edit this file directly; it is tangled from init.org
;;; Code:


(set-default-coding-systems 'utf-8)

(customize-set-variable 'custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
(load custom-file))

(defvar bootstrap-version)
  (let ((bootstrap-file
	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
	(bootstrap-version 5))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
	  (url-retrieve-synchronously
	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	   'silent 'inhibit-cookies)
	(goto-char (point-max))
	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(customize-set-variable 'straight-use-package-by-default t)

(use-package no-littering)

(use-package general
  :demand t
  :config
  (general-evil-setup)
  (general-create-definer mapleader
    :prefix "SPC"
    :global-prefix "C-SPC"
    :keymaps 'override
    :states '(normal visual emacs insert))
    (mapleader
  "b" '(:ignore t :which-key "Buffer management")
  "bb" '(switch-to-buffer :which-key "Buffer management")
  "bi" '(ibuffer :which-key "Interactive buffer management")
  "bn" '(next-buffer :which-key "Next buffer")
  "bd" '(evil-delete-buffer :which-key "Kill a buffer")
  "bp" '(previous-buffer :which-key "Previous buffer")
  "br" '(revert-buffer :which-key "Revert the current buffer")
  "f" '(:ignore t :which-key "Files")
  "ff" '(find-file :which-key "Find a file on disk")
  "fs" '(save-buffer :which-key "Save changes")
  "F" '(:ignore t :which-key "Frames")
  "Fo" '(other-frame :which-key "Other frame")
  "g" '(:ignore t :which-key "Git operations")
  "h" '(:ignore t :which-key "Get help")
  "hc" '(:ignore t :which-key "Customization")
  "hcc" '(customize :which-key "The main custommize interface")
  "hcf" '(customize-face :which-key "Customize a face")
  "hcg" '(customize-group :which-key "Customize a particular group")
  "hcv" '(customize-variable :which-key "Customize a specific variable")
  "hd" '(:ignore t :which-key "Describe parts of Emacs")
  "hdb" '(describe-bindings :which-key "Describe the bindings that are in effect")
  "hdB" '(general-describe-keybindings :which-key "Show the bindings that General has defined.")
  "hdf" '(describe-function :which-key "Describe a function")
  "hdF" '(describe-face :which-key "Describe a face")
  "hdk" '(describe-key :which-key "Show the documentation for the function associated with key")
  "hdm" '(describe-mode :which-key "Describe the current mode")
  "hdv" '(describe-variable :which-key "Show the docs for a variable")
  "hi" '(:ignore t :which-key "info things")
  "hia" '(info-apropos :which-key "Search for matches of a term in the database")
  "hii" '(info :which-key "Enter the info index")
  "him" '(info-display-manual :which-key "Open a manual directly")
  "q" '(:ignore t :which-key "Closing Emacs itself or frames within.")
  "qq" '(save-buffers-kill-terminal :which-key "Save the open buffers and close this connection")
  "qQ" '(kill-emacs :which key "Kill Emacs permanently")))

(use-package exec-path-from-shell

  :config
  (exec-path-from-shell-initialize))

(add-to-list 'load-path (expand-file-name "emacspeak/lisp/" user-emacs-directory))

(use-package emacs
  :straight nil
  :custom
  (auto-save-name-transforms `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
  (inhibit-startup-message t)
   (indent-tabs-mode nil)
   (tool-bar-mode nil)
   (menu-bar-mode nil)
   (scroll-bar-mode nil)
   (user-full-name "Hunter Jozwiak")
   (user-mail-address "hunter.t.joz@gmail.com")
   (user-login-name "sektor")
   (use-short-answers t))

(use-package autorevert
  :straight nil
  :custom
  (auto-revert-interval 0.1)
:config
    (global-auto-revert-mode))

(use-package recentf
  :straight nil
  :config (recentf-mode))

(use-package savehist
  :straight nil
  :config (savehist-mode))

(use-package windmove
  :straight nil
  :general
  (mapleader
    "w" '(:ignore t :which-key "Window operations")
    "wh" '(windmove-left :which-key "Select the window to the left")
    "wl" '(windmove-right :which-key "Select the window to the right")
    "wj" '(windmove-down :which-key "Select the window below")
    "wk" '(windmove-up :which-key "Select window above")))
(use-package winner
  :straight nil
    :general
    (mapleader
      "wr" '(winner-redo :which-key "Restore a window configuration")
      "wu" '(winner-redo :which-key "Restore a window configuration"))
    :config
    (winner-mode))

(use-package auth-source
  :straight nil
  :custom
  (auth-source-cache-expiry nil))
(use-package auth-source-pass
  :straight nil
  :custom
  (auth-sources '("~/.authinfo.gpg" password-store))
  :config
  (auth-source-pass-enable))

(use-package epa
  :straight nil
  :custom
  (epa-pinentry-mode 'loopback))

(use-package emacspeak-setup
  :straight nil
  :custom
  (espeak-default-speech-rate 820)
   (emacspeak-character-echo nil)
   (emacspeak-word-echo nil))

(use-package orderless
  :ensure t
  :custom
  (completion-category-overrides '((file (styles . (basic partial-completion)))))
  (completion-styles '(orderless basic)))

(use-package vertico
  :custom (vertico-count 20)
           (vertico-cycle t)
  :general
   (vertico-map
   "C-J" 'vertico-next
   "C-k" 'vertico-previous)
   :init
   (vertico-mode 1))
(add-to-list 'load-path (expand-file-name "straight/build/vertico/extensions" user-emacs-directory))
(use-package vertico-directory
  :straight nil
             :after vertico
    :general
     (vertico-map
     "C-l" 'vertico-directory-enter
     "C-h" 'vertico-directory-up))

(use-package marginalia
  :config (marginalia-mode))

(use-package consult
  :custom
  (completion-in-region-function #'consult-completion-in-region)
  :general
   ([remap switch-to-buffer] 'consult-buffer))

(use-package embark
  :general
   ([remap describe-bindings] 'embark-bindings
   "C-." 'embark-act))

(use-package embark-consult
             :after (embark consult)
    :hook (embark-collect-mode . consult-preview-at-point-mode))

(use-package company

  :custom
  (company-minimum-prefix-length 1)
  (company-idle-delay 0.0)
  :init
  (global-company-mode))
(use-package company-box

  :hook (company-mode . company-box-mode))

(use-package yasnippet

  :init
  (yas-global-mode 1))
(use-package yasnippet-snippets

  :after yasnippet)

(use-package org
  :demand t
  :custom (org-directory "~/org")
  (org-return-follows-link t)
  :preface
  (defun org-setup ()
    "Hook functions for when we enter an org buffer, not provided by any other major mode."
    (prettify-symbols-mode 1)
    (variable-pitch-mode 1))
  :hook (org-mode . org-setup))

(use-package org-appear

  :after org
  :hook (org-mode . org-appear-mode))

(use-package evil-org

  :after org
  :hook (org-mode . evil-org-mode)
  :config
  (require 'evil-org-agenda)
  (evil-org-agenda-set-keys))

(use-package org-make-toc)

(use-package eglot
  :commands eglot-ensure
  :custom
  (eglot-autoshutdown t))

(use-package flycheck
  :init
  (global-flycheck-mode 1))

(use-package smartparens

  :init
  (smartparens-strict-mode 1))

(use-package sly
  :custom (inferior-lisp-program "sbcl")
  :hook (lisp-mode . sly-editing-mode))
(use-package sly-asdf
  :after sly)
(use-package sly-quicklisp
  :after sly)

(use-package geiser
  :custom (scheme-program-name "guile"))
(use-package geiser-guile)

(use-package rustic)

(use-package yaml-mode
  :hook (yamml-mode . eglot-ensure))

(use-package project
  :straight nil
  :general
  (mapleader
    "SPC" '(consult-project-buffer :which-key "Switch to a buffer in a project")
    "p" '(:ignore t :which-key "Project operations.")
    "pc" '(project-compile :which-key "Compile the project")
    "pd" '(project-dired :which-key "Open a dired buffer for this project")
    "pe" '(project-eshell :which-key "Open esheel for this project")
    "pf" '(project-find-file :which-key "Search for a file within a project")
    "pp" '(project-switch-project :which-key "Switch to a project")
    "ps" '(magit-project-status :which-key "Git status of a project")
    :init
    (unless (file-exists-p project-list-file)
      (project-remember-projects-under "~/projects")
      (project-remember-project "~/.emacs.d/"))))

(use-package magit
  :demand t
  :custom
  (magit-delete-by-moving-to-trash nil)
  :commands magit-add-section-hook magit-status magit-stage-file
  :general
  (mapleader
    "gg" '(magit-status :which-key "Magit status")
    "gs" '(magit-stage-file :which-key "Stage the current working file."))
  :config
  (magit-add-section-hook 'magit-status-sections-hook 'magit-insert-modules 'magit-insert-stashes 'append))

(use-package forge
             :after magit
             :general
             (mapleader
               "gf" '(forge-dispatch :which-key "Forge dispatching map.")))

(use-package magit-gitflow

    :hook (magit-mode . turn-on-magit-gitflow))

(use-package git-timemachine
    :general
    (mapleader
      "gt" '(git-timemachine-toggle :which-key "Toggle the time machine")))

(use-package nix-mode
  :mode "\\.nix\\'")

(use-package kubernetes
  :general
  (mapleader
    "k" '(:ignore t :which-key "Kubernetes operations")
    "ko" '(kubernetes-overview :which-key "Get an overview")))

(use-package helpful

  :general
   ([remap describe-function] 'helpful-callable
   [remap describe-key] 'helpful-key
   [remap describe-variable] 'helpful-variable))

(use-package which-key

  :init
  (which-key-mode 1))

(use-package restart-emacs

  :general
  (mapleader
   "qr" '(restart-emacs :which-key "Restart Emacs")))

(use-package undo-tree
  :init
  (global-undo-tree-mode 1))

(use-package evil
             :custom
             (evil-want-integration t)
             (evil-want-C-i-jump nil)
             (evil-want-keybind nil)
             (evil-undo-system 'undo-tree)
             :init
             (evil-mode 1))

(use-package evil-collection
             :after evil
             :config
             (evil-collection-init))

(use-package ement
  :demand t
  :straight (ement :type git :host github :repo "alphapapa/ement.el")
  :custom
  (ement-save-sessions t)
  (ement-initial-sync-timeout 10000)
  :hook (ement-room-compose . ement-room-compose-org))

(use-package notmuch
  :straight nil)

(use-package mastodon)

(use-package twittering-mode
  :custom
(twittering-auth-method 'oauth)
  (twittering-use-master-password t)
  (twittering-oauth-invoke-browser t)
  (twittering-allow-insecure-server-cert t))

;;; init.el ends here
